ai:
  primary: gemini
  selected_tools:
  - gemini
conventions:
  branch_naming: '{number:03d}-{feature-name}'
  plan_naming: plan-{number:03d}.md
  spec_naming: spec-{number:03d}.md
  task_naming: task-{number:03d}.md
project:
  created: '2025-11-30T03:24:03.538465'
  name: Sahibinden.next
  type: web
templates:
  plan: .specpulse/templates/plan.md
  spec: .specpulse/templates/spec.md
  task: .specpulse/templates/task.md
version: 2.7.4
